### ISSUE TITLE
App组件是如何与Redux store连接的？

### ISSUE THREAD

**Issue by liuyi999111** [JasonStu/RN-BiZhi#1]
你好，我是个RN的初学者，我在官方例子中看到使用Redux需要连接组件和store,使用了’react-redux‘中的connect函数连接，但是我在你的示例中没有看到，如果没有这一步骤，如何分发Action,统一管理state呢？

**Comment by JasonStu** [comment]
你可能要花时间去看看官方的redux的介绍==>  http://cn.redux.js.org 去看一下 我demo里面是有,不然我项目都不会正常运行啦
